/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use TestNG framework, also requires calling test.useTestNG() below
    implementation(libs.testng)
    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)
    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)
    implementation(libs.selenium)
    implementation(libs.restassured)
    implementation(libs.jacksondatabind)
    implementation(libs.extentreports)
    implementation(libs.apachecommons)
    implementation(libs.logback)
    implementation(libs.cucumberjava)
    implementation(libs.cucumbertestng)
    implementation(libs.picocontainer)
    implementation(libs.javanativeaccess)
    implementation(libs.grasshopper)
    implementation(libs.javafaker) {
        exclude(module = "snakeyaml")
    }

}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named<Test>("test") {
    // Use TestNG for unit tests.
    useTestNG()
    isScanForTestClasses = false
    testLogging.showStandardStreams = true
}


tasks.register<Test>("allTests") {

    isScanForTestClasses = false
    useTestNG(){
        suites("src/test/resources/testsuites/testng.xml")
    }
}

tasks.register<Test>("guiTests") {

    isScanForTestClasses = false
    useTestNG(){
        suites("src/test/resources/testsuites/testngGui.xml")
    }
}

tasks.register<Test>("apiTests") {

    isScanForTestClasses = false
    useTestNG(){
        suites("src/test/resources/testsuites/testngApi.xml")
    }
}

tasks.register<Test>("smokeTests") {

    isScanForTestClasses = false
    useTestNG(){
        suites("src/test/resources/testsuites/testngSmoke.xml")
    }
}